### ISSUE TITLE
rewards image not showing

### ISSUE THREAD

**Issue by sniffski** [helikon-labs/polkadot-kusama-1kv-telegram-bot#69]
When I call /rewards and choose my validator from list... Nothing happens...

In the log, error is:
```
MongoError: text index required for $text query
    at MessageStream.messageHandler (/home/<username>/polkadot-kusama-1kv-telegram-bot/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (node:events:527:28)
    at processIncomingData (/home/<username>/polkadot-kusama-1kv-telegram-bot/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/<username>/polkadot-kusama-1kv-telegram-bot/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at MessageStream.Writable.write (node:internal/streams/writable:335:10)
    at Socket.ondata (node:internal/streams/readable:777:22)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12) {
  ok: 0,
  code: 27,
  codeName: 'IndexNotFound'
}
```

**Comment by kukabi** [comment]
@sniffski Thanks for the report and sorry for not adding this to the readme. You need to add a text index to the `validators` collection in the MongoDB database. You can do it using the Mongo CLI, example below assumes your database name is configured as `kusama_1kv_bot` in your `.env` file in the root.

First select the database:

```
use kusama_1kv_bot
```

Then create the index:

```
db.validators.createIndex( { name: "text" } )
```

And you should be able to run the commands.

**Comment by kukabi** [comment]
Updated the readme.

**Comment by kukabi** [comment]
@sniffski Every 100th block (about every 10 minutes) the bot is going to try to index the reward data from the node. It starts from block 0 and eventually moves up to the current block height, storing the reward events as it moves, but with Kusama at about 12 million blocks, it's going to take a very very long time to complete fetching the data especially if you're not connecting the bot to a local archive node. It can be faster if you're using a local archive node.

If you're running the bot at the moment then it probably did start the data-fetching process, you should be seeing the logs similar to `Did fetch and save 0 rewards in block #818`.

So one solution could be to start indexing from more recent blocks. Two ways to do this.

One is to edit the following function in `modules/data.js`, delete the MongoDB data and restart the bot, so that the bot starts indexing from, say, block 11000000:

```javascript
async function getLastFetchedRewardBlock() {
    let rewardFetchInfoCollection = await MongoDB.getRewardFetchInfoCollection();
    let rewardFetchInfo = await rewardFetchInfoCollection.findOne({});
    if (!rewardFetchInfo) {
        logger.info(`Reward fetch info not found in db, saving.`);
        let info = { lastFetchedBlockNumber: 10999999 }; // !!!! <---- indexing will start from +1 of this value 
        await rewardFetchInfoCollection.insertOne(info);
        rewardFetchInfo = await rewardFetchInfoCollection.findOne({});
    }
    return rewardFetchInfo.lastFetchedBlockNumber;
}
```

The other is to edit the value manually. Stop the bot. There's a single record in the `reward_fetch_info` collection in the MongoDB database. Edit that record and set it to the following to start the indexing from 11000000 next time:

```json
{ lastFetchedBlockNumber: 10999999 }
```

Restart the bot, and the next time it starts indexing, it's going to start with block 11000000. Wait until the indexing completes up to the current block, then you should be able to view your reward reports.
